# Generated by Django 4.2.11 on 2024-03-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_order_paid_order_is_paid_order_merchant_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
